description=Servizio di test
resourcePath=test/junitapi/v1
serviceScope=External Channel
functionalDomain=Gestioni Patrimoniali
apiCategory=Private
serviceApplicationOwner=Aletti Planet (ALPLA)
supportedBanks=Banca Aletti
