description=Lo scopo del servizio è esporre funzionalità relative alle verifiche e gli adempimenti delle normative antiriciclaggio, relativamente all'ambito del GestioneDelCredito.
resourcePath=gdc01/GestioneDelCreditoAntiriciclaggioService/v1
serviceScope=External Channel
functionalDomain=Credito
apiCategory=Private
serviceApplicationOwner=Gestione AntiRiciclaggio
supportedBanks=Imola
